const svg = d3.select("#chart-area").append("svg")
  .attr("width", 400)
  .attr("height", 400)

svg.append("rect")
  .attr("x", 100)
  .attr("y", 250)
  .attr("width", 200)
  .attr("height", 70)
  .attr("fill", "blue")